CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    login_id VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX ix_users_login_id ON users (login_id);

CREATE TABLE upbit_api_keys (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    access_key_encrypted CLOB NOT NULL,
    secret_key_encrypted CLOB NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_upbit_api_keys_user_id
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX ix_upbit_api_keys_user_id ON upbit_api_keys (user_id);

CREATE TABLE trading_bots (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    api_key_id NUMBER,
    name VARCHAR2(100) NOT NULL,
    market VARCHAR2(30) DEFAULT 'KRW-USDT' NOT NULL,
    trade_mode VARCHAR2(20) DEFAULT 'paper' NOT NULL,
    strategy_type VARCHAR2(50) DEFAULT 'premium_rebalance' NOT NULL,
    bot_status VARCHAR2(30) DEFAULT 'STOPPED' NOT NULL,
    last_signal VARCHAR2(20) DEFAULT 'HOLD' NOT NULL,
    last_signal_at TIMESTAMP WITH TIME ZONE,
    last_error CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_trading_bots_user_id
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_trading_bots_api_key_id
        FOREIGN KEY (api_key_id) REFERENCES upbit_api_keys (id)
);

CREATE INDEX ix_trading_bots_user_id ON trading_bots (user_id);

CREATE TABLE bot_settings (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bot_id NUMBER NOT NULL,
    initial_balance BINARY_DOUBLE DEFAULT 100000000 NOT NULL,
    buy_premium_threshold BINARY_DOUBLE DEFAULT -0.3 NOT NULL,
    sell_premium_threshold BINARY_DOUBLE DEFAULT 0.3 NOT NULL,
    neutral_band BINARY_DOUBLE DEFAULT 0.1 NOT NULL,
    base_price BINARY_DOUBLE,
    price_gap BINARY_DOUBLE DEFAULT 3.0 NOT NULL,
    round_trip_fee_rate BINARY_DOUBLE DEFAULT 0.001 NOT NULL,
    max_order_amount BINARY_DOUBLE DEFAULT 10000000 NOT NULL,
    daily_max_trade_amount BINARY_DOUBLE DEFAULT 50000000 NOT NULL,
    daily_max_loss_rate BINARY_DOUBLE DEFAULT -1.0 NOT NULL,
    fx_provider VARCHAR2(20) DEFAULT 'manual' NOT NULL,
    manual_usd_krw_rate BINARY_DOUBLE DEFAULT 1370.0 NOT NULL,
    fx_rate_max_stale_seconds NUMBER DEFAULT 300 NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_bot_settings_bot_id UNIQUE (bot_id),
    CONSTRAINT fk_bot_settings_bot_id
        FOREIGN KEY (bot_id) REFERENCES trading_bots (id)
);

CREATE TABLE price_snapshots (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    bot_id NUMBER NOT NULL,
    market VARCHAR2(30) NOT NULL,
    trade_price BINARY_DOUBLE NOT NULL,
    bid_price BINARY_DOUBLE NOT NULL,
    ask_price BINARY_DOUBLE NOT NULL,
    usd_krw_rate BINARY_DOUBLE,
    premium_rate BINARY_DOUBLE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_price_snapshots_user_id
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_price_snapshots_bot_id
        FOREIGN KEY (bot_id) REFERENCES trading_bots (id)
);

CREATE INDEX ix_price_snapshots_user_id ON price_snapshots (user_id);
CREATE INDEX ix_price_snapshots_bot_id ON price_snapshots (bot_id);

CREATE TABLE trades (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    bot_id NUMBER NOT NULL,
    side VARCHAR2(20) NOT NULL,
    price BINARY_DOUBLE NOT NULL,
    volume BINARY_DOUBLE NOT NULL,
    fee BINARY_DOUBLE NOT NULL,
    profit BINARY_DOUBLE NOT NULL,
    profit_rate BINARY_DOUBLE NOT NULL,
    total_asset_krw BINARY_DOUBLE NOT NULL,
    trade_mode VARCHAR2(20) DEFAULT 'paper' NOT NULL,
    status VARCHAR2(30) DEFAULT 'FILLED' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_trades_user_id
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_trades_bot_id
        FOREIGN KEY (bot_id) REFERENCES trading_bots (id)
);

CREATE INDEX ix_trades_user_id ON trades (user_id);
CREATE INDEX ix_trades_bot_id ON trades (bot_id);
